Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace ExpenseTracker.Models
{
    public class Category
    {
        [Key]
        public int CategoryId { get; set; }

        [System.ComponentModel.DataAnnotations.Required]

        public string CategoryName { get; set; } = string.Empty;
    
        public double CategoryAmount { get; set; }
    }
}

Models/Expense.cs
using System.ComponentModel.DataAnnotations;

namespace ExpenseTracker.Models
{
    public class Expense
    {
        [Key]
        public int ExpenseId { get; set; }

        [Required]
        public string ExpenseTitle { get; set; } = string.Empty;

        [Required]
        public double ExpenseAmount { get; set; }

        public string ExpenseDescription { get; set; } = string.Empty;

        public int CategoryId { get; set; }

        public Category? Category { get; set; }

        public DateTime Date { get; set; } = DateTime.Today;
    }
}

Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseTracker.Models;

namespace ExpenseTracker.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly AppDbContext _context;

        public CategoriesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            try
            {
            var data = await _context.Categories.ToListAsync();
              return View(data);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,CategoryName,CategoryAmount")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,CategoryName,CategoryAmount")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'AppDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }


        private bool CategoryExists(int id)
        {
          return _context.Categories.Any(e => e.CategoryId == id);
        }
    }
}

Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseTracker.Models;

namespace ExpenseTracker.Controllers
{
    public class ExpensesController : Controller
    {
        private readonly AppDbContext _context;

        public ExpensesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Expenses
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Expenses.Include(e => e.Category);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Expenses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Expenses == null)
            {
                return NotFound();
            }

            var expense = await _context.Expenses
                .Include(e => e.Category)
                .FirstOrDefaultAsync(m => m.ExpenseId == id);
            if (expense == null)
            {
                return NotFound();
            }

            return View(expense);
        }

        // GET: Expenses/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Expenses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExpenseId,ExpenseTitle,ExpwenseAmount,ExpenseDescription,CategoryId,Date")] Expense expense)
        {
            if (ModelState.IsValid)
            {
                _context.Add(expense);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", expense.CategoryId);
            return View(expense);
        }

        // GET: Expenses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Expenses == null)
            {
                return NotFound();
            }

            var expense = await _context.Expenses.FindAsync(id);
            if (expense == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", expense.CategoryId);
            return View(expense);
        }

        // POST: Expenses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExpenseId,ExpenseTitle,ExpwenseAmount,ExpenseDescription,CategoryId,Date")] Expense expense)
        {
            if (id != expense.ExpenseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(expense);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpenseExists(expense.ExpenseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", expense.CategoryId);
            return View(expense);
        }

        // GET: Expenses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (_context.Expenses == null)
            {
                return Problem("Entity set 'AppDbContext.Expenses'  is null.");
            }
            var expense = await _context.Expenses.FindAsync(id);
            if (expense != null)
            {
                _context.Expenses.Remove(expense);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }

        private bool ExpenseExists(int id)
        {
          return _context.Expenses.Any(e => e.ExpenseId == id);
        }
    }
}

Controllers/TotalExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseTracker.Models;

namespace ExpenseTracker.Controllers
{
    public class TotalExpensesController : Controller
    {
        private readonly AppDbContext _context;

        public TotalExpensesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: TotalExpenses
        public async Task<IActionResult> Index()
        {
              return View(await _context.TotalExpense.ToListAsync());
        }

        // GET: TotalExpenses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TotalExpense == null)
            {
                return NotFound();
            }

            var totalExpense = await _context.TotalExpense
                .FirstOrDefaultAsync(m => m.TotalExpenseId == id);
            if (totalExpense == null)
            {
                return NotFound();
            }

            return View(totalExpense);
        }

        // GET: TotalExpenses/Create
        public IActionResult Create()
        {
            var totalExpense = _context.TotalExpense.Count() > 0 ? 1 : 0;
            if(totalExpense >= 1)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        // POST: TotalExpenses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TotalExpenseId,TotalExpenseLimit")] TotalExpense totalExpense)
        {
            if (ModelState.IsValid)
            {
                _context.Add(totalExpense);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(totalExpense);
        }

        // GET: TotalExpenses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TotalExpense == null)
            {
                return NotFound();
            }

            var totalExpense = await _context.TotalExpense.FindAsync(id);
            if (totalExpense == null)
            {
                return NotFound();
            }
            return View(totalExpense);
        }

        // POST: TotalExpenses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TotalExpenseId,TotalExpenseLimit")] TotalExpense totalExpense)
        {
            if (id != totalExpense.TotalExpenseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(totalExpense);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TotalExpenseExists(totalExpense.TotalExpenseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(totalExpense);
        }

        // GET: TotalExpenses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TotalExpense == null)
            {
                return NotFound();
            }

            var totalExpense = await _context.TotalExpense
                .FirstOrDefaultAsync(m => m.TotalExpenseId == id);
            if (totalExpense == null)
            {
                return NotFound();
            }

            return View(totalExpense);
        }

        // POST: TotalExpenses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TotalExpense == null)
            {
                return Problem("Entity set 'AppDbContext.TotalExpense'  is null.");
            }
            var totalExpense = await _context.TotalExpense.FindAsync(id);
            if (totalExpense != null)
            {
                _context.TotalExpense.Remove(totalExpense);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TotalExpenseExists(int id)
        {
          return _context.TotalExpense.Any(e => e.TotalExpenseId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css">
        <link href="~/css/site.css" rel="stylesheet" />
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@700&family=Lexend:wght@300;400;500;600&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/f2157c640c.js" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <header>
        <img src="~/img/imglogo.png" />
        <nav class="navbar">
          <ul>
                <li><a class="" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a class="" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                <li><a class="" asp-area="" asp-controller="Expenses" asp-action="Index">Expenses</a></li>
                <li><a class="" asp-area="" asp-controller="TotalExpenses" asp-action="Index">Total Expenses</a></li>
          </ul>
          
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init({
            offset: 300,
            duration: 1000,
        });

    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_category.cshtml
@model IEnumerable<ExpenseTracker.Models.Category>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryAmount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryAmount)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.CategoryId">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.CategoryId">Details</a>
                    <a asp-action="Delete" asp-route-ID="@item.CategoryId" onclick="return confirm('Are you sure you wish to Delete?');">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_expense.cshtml
@model IEnumerable<ExpenseTracker.Models.Expense>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">@Html.DisplayNameFor(model => model.ExpenseTitle)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.ExpenseAmount)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.ExpenseDescription)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Category)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Date)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">1</th>
                <td>@Html.DisplayFor(modelItem => item.ExpenseTitle)</td>
                <td>@Html.DisplayFor(modelItem => item.ExpenseAmount)</td>
                <td>@Html.DisplayFor(modelItem => item.ExpenseDescription)</td>
                <td>@Html.DisplayFor(modelItem => item.Category.CategoryName)</td>
                <td>@Html.DisplayFor(modelItem => item.ExpenseDescription)</td>
                <td>@Html.DisplayFor(modelItem => item.Date)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ExpenseId">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.ExpenseId">Details</a>
                    <a asp-action="Delete" asp-route-ID="@item.ExpenseId" onclick="return confirm('Are you sure you wish to Delete?');">
                        <i class="bi bi-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>